### ISSUE TITLE
Readme is not consistent with the example readme.

### ISSUE THREAD

**Issue by spshetty** [SoftwareEngineeringToolDemos/ICSE-2011-Miler#9]
The example repo has the following format for some links to the original project:
- The Official Project Page, including source code
- The Tool on the Visual Studio Gallery
- A Video of the Tool

Whereas in this readme, it has been given as:
- Original-Project-Page.
- Original-demo-link.

The attribution part at bottom is not in the format as stated in example-repo

**Comment by saileshbvk** [comment]
Closed #9
